#!/bin/sh
swaymsg -t get_tree |
 jq -r '.nodes[].nodes[] | if .nodes then [recurse(.nodes[])] else [] end + .floating_nodes | .[] | select(.nodes==[]) | ((.id | tostring) +  "\t"  + .name)' |
 wofi --show dmenu | {
IFS=$'\t' read -r id name
swaymsg 'mouse_warping container'
swaymsg "[con_id=$id]" focus
swaymsg 'mouse_warping output'
echo "ID=$id NAME=$name"
}
